from pathlib import Path
import hashlib, json, re, sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(name, cond):
    ok=bool(cond); checks.append((name,ok)); print(('PASS' if ok else 'FAIL')+' - '+name)
def text(p): return (ROOT/p).read_text(encoding='utf-8')
required=['src/Program.cs','build.ps1','install.ps1','uninstall.ps1','SignalFlow-Mini.ps1','INSTALL-SIGNALFLOW-MINI.cmd','BUILD-AND-INSTALL.cmd','README.md','OWNER-TEST-CHECKLIST.md','VERSION','AGENTS.md','SOUL.md','LOCK.json','evidence.json','LICENSE','NOTICE','THIRD-PARTY-NOTICES.md','docs/ORIGIN-AND-LINEAGE.md','assets/Signalproof.ico']
program=text('src/Program.cs'); installer=text('install.ps1'); build=text('build.ps1')
check('01 required public package files', all((ROOT/p).is_file() for p in required))
check('02 SignalFlow Mini version identity', text('VERSION').strip()=='SIGNALFLOW-MINI-V1-RD2-OVERLAY-2026-09-03')
check('03 public UI rebranded', 'SignalFlow Mini - Ready' in program and 'ReoFlow - Ready' not in program)
check('04 executable rebranded', 'SignalFlow-Mini.exe' in build and 'SignalFlow-Mini.exe' in installer)
check('05 install root rebranded', "LOCALAPPDATA 'SignalFlow-Mini'" in installer)
check('06 F8 global hook preserved', 'VK_F8 = 0x77' in program and 'WH_KEYBOARD_LL' in program)
check('07 microphone capture preserved', 'MemoryStream _pcm' in program and 'waveInOpen' in program)
check('08 PCM 16k mono 16-bit preserved', 'nSamplesPerSec = 16000' in program and 'wBitsPerSample = 16' in program)
check('09 500 ms pre-roll preserved', 'PreRollMilliseconds = 500' in program and 'CopyPreRollTo(_pcm)' in program)
check('10 650 ms post-roll preserved', 'PostRollMilliseconds = 650' in program and 'Task.Delay(PostRollMilliseconds)' in program)
check('11 local whisper preserved', 'whisper-cli.exe' in program and '-l en -nt -np' in program)
check('12 clipboard recovery preserved', 'Clipboard.SetText(text)' in program)
check('13 guarded browser paste preserved', 'SendInput' in program and 'GetForegroundWindow() != _targetWindow' in program)
check('14 classic paste timeout preserved', 'SendMessageTimeout' in program and '2000' in program)
check('15 focus guard preserved', 'CapturePasteTarget' in program and 'focusedNow != _targetControl' in program)
check('16 legacy mutual exclusion preserved', 'Local\\\\ReoSpeak-RD3-OwnerTest' in program)
check('17 quick tap guard preserved', 'held.TotalMilliseconds < 220' in program)
check('18 temp WAV lifecycle preserved', 'File.WriteAllBytes(wavPath' in program and 'File.Delete(wavPath)' in program)
check('19 no normal control UI', 'START TALKING' not in program and 'FormStartPosition.CenterScreen' not in program)
check('20 taskbar host retained', 'ShowInTaskbar = true' in program and 'WS_EX_APPWINDOW' in program)
check('21 host noactivate', 'WS_EX_NOACTIVATE' in program and 'ShowWithoutActivation' in program)
check('22 overlay not taskbar', 'class AudioOverlayForm' in program and 'ShowInTaskbar = false' in program)
check('23 overlay topmost', 'TopMost = true' in program)
check('24 overlay click-through', 'WS_EX_TRANSPARENT' in program and 'HTTRANSPARENT' in program)
check('25 listening overlay state', '_overlay.ShowListening(_targetWindow)' in program)
check('26 processing overlay state', '_overlay.ShowProcessing(_targetWindow)' in program)
check('27 overlay auto hide', '_autoHideTick' in program and 'HideOverlay()' in program)
check('28 pinned model hash', 'c6138d6d58ecc8322097e0f987c32f1be8bb0a18532a3f88f734d1bbf9c41e5d' in installer)
check('29 pinned whisper archive hash', 'b07ea0b1b4115a38e1a7b07debf581f0b77d999925f8acb8f39d322b0ba0a822' in installer)
check('30 atomic stage/rollback retained', '.SignalFlow-Mini-stage-' in installer and '.SignalFlow-Mini-backup-' in installer and 'Move-Item $backup $installRoot' in installer)
check('31 Apache 2.0 present', 'Apache License' in text('LICENSE') and 'Version 2.0' in text('LICENSE'))
check('32 lineage records exact owner source package', 'ReoFlow-V1-RD2-Overlay-Owner-Test-2026-09-03.zip' in text('docs/ORIGIN-AND-LINEAGE.md'))
joined='\n'.join(text(p) for p in required if (ROOT/p).suffix.lower() in {'.cs','.ps1','.md','.cmd','.json'})
secrets=re.findall(r'(?i)(api[_-]?key|secret|token)\s*[=:]\s*["\'][^"\']{8,}',joined)
check('33 no embedded secret assignments', not secrets)
failed=[n for n,ok in checks if not ok]
print(f'\nRESULT: {len(checks)-len(failed)}/{len(checks)} checks passed')
if failed:
    print('FAILED: '+', '.join(failed)); sys.exit(1)
